# headers and icon 
title: Patricia de Torres Coll
info: bscs'24 @ uta
icon-pic: assets/img/photo.jpg

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
